import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'polish_widgets.dart';

class ConversationInvitePage extends StatefulWidget {
  final String conversationId, title, type;
  const ConversationInvitePage({super.key, required this.conversationId, required this.title, required this.type});
  @override State<ConversationInvitePage> createState()=>_ConversationInvitePageState();
}
class _ConversationInvitePageState extends State<ConversationInvitePage>{
  final db=Supabase.instance.client; String? code; bool loading=true,busy=false;
  bool get channel=>widget.type=='channel';
  String get link=>code==null?'':'https://bkbdcqequyvubjmrbpqo.supabase.co/functions/v1/invite-redirect?code=${Uri.encodeComponent(code!)}';
  void toast(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
  Future<void> load()async{try{final r=await db.from('conversations').select('invite_code').eq('id',widget.conversationId).maybeSingle();if(mounted)setState((){code=(r?['invite_code']??'').toString().trim().isEmpty?null:r!['invite_code'].toString();loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
  Future<void> make()async{if(busy)return;setState(()=>busy=true);try{final r=await db.rpc('create_conversation_invite',params:{'p_conversation_id':widget.conversationId,'p_max_uses':0,'p_expires_at':null,'p_requires_approval':false});if(mounted)setState(()=>code=r.toString());toast('لینک ${channel?'کانال':'گروه'} ساخته شد.');}catch(e){toast('ساخت لینک ناموفق بود: $e');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> revoke()async{if(code==null||busy)return;setState(()=>busy=true);try{await db.rpc('revoke_conversation_invite',params:{'p_conversation_id':widget.conversationId});if(mounted)setState(()=>code=null);toast('لینک باطل شد.');}catch(e){toast('باطل کردن لینک ناموفق بود: $e');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> copy(String s)async{await Clipboard.setData(ClipboardData(text:s));toast('کپی شد.');}
  Future<void> share()async{if(link.isNotEmpty)await Share.share('${widget.title}\n${channel?'لینک کانال':'لینک گروه'}:\n$link\nکد: $code');}
  @override void initState(){super.initState();load();}
  @override Widget build(BuildContext context){if(loading)return Scaffold(appBar:AppBar(title:Text(channel?'لینک کانال':'لینک گروه')),body:const AppSkeletonList(count: 5));return Scaffold(appBar:AppBar(title:Text(channel?'لینک کانال':'لینک گروه')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Icon(channel?Icons.campaign_rounded:Icons.groups_rounded,size:48,color:Theme.of(context).colorScheme.primary),const SizedBox(height:10),Text(widget.title,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(channel?'لینک دعوت کانال':'لینک دعوت گروه')])),),const SizedBox(height:12),if(code==null)Card(child:ListTile(leading:const Icon(Icons.link_off),title:Text('لینک ${channel?'کانال':'گروه'} وجود ندارد'),subtitle:const Text('لینک جدید بسازید.'),trailing:FilledButton(onPressed:busy?null:make,child:const Text('ساخت')))),if(code!=null)...[Card(child:ListTile(leading:const Icon(Icons.link),title:const Text('لینک دعوت'),subtitle:SelectableText(link),trailing:IconButton(onPressed:()=>copy(link),icon:const Icon(Icons.copy)))),Card(child:ListTile(leading:const Icon(Icons.key),title:const Text('کد دعوت'),subtitle:SelectableText(code!),trailing:IconButton(onPressed:()=>copy(code!),icon:const Icon(Icons.copy)))),FilledButton.icon(onPressed:busy?null:share,icon:const Icon(Icons.share),label:const Text('اشتراک‌گذاری')),OutlinedButton.icon(onPressed:busy?null:make,icon:const Icon(Icons.autorenew),label:const Text('ساخت لینک جدید')),TextButton.icon(onPressed:busy?null:revoke,icon:const Icon(Icons.link_off),label:const Text('باطل کردن لینک'))],if(busy)const Padding(padding:EdgeInsets.all(16),child:Center(child:CircularProgressIndicator()))]));}
}

class ChannelManagementPage extends StatefulWidget{
  final String conversationId,title;
  const ChannelManagementPage({super.key,required this.conversationId,required this.title});
  @override State<ChannelManagementPage> createState()=>_ChannelManagementPageState();
}
class _ChannelManagementPageState extends State<ChannelManagementPage>{
  final db=Supabase.instance.client; Map<String,dynamic>? c; bool loading=true,busy=false,canManage=false;
  bool get owner=>c!=null&&c!['created_by']?.toString().isEmpty==false&&c!['created_by'].toString()==db.auth.currentUser?.id;
  void toast(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
  Future<void> load()async{try{final r=await db.from('conversations').select('id,type,title,description,avatar_url,created_by,username,is_public,join_approval,only_admins_can_post,only_admins_can_add,allow_reactions,auto_delete_seconds').eq('id',widget.conversationId).single();final uid=db.auth.currentUser?.id;final m=uid==null?null:await db.from('conversation_members').select('role').eq('conversation_id',widget.conversationId).eq('user_id',uid).maybeSingle();final role=m?['role']?.toString();final memberAdmin=role=='admin'||role=='owner';if(mounted)setState((){c=Map<String,dynamic>.from(r);canManage=owner||memberAdmin;loading=false;});}catch(e){if(mounted){setState(()=>loading=false);toast('مدیریت کانال بارگذاری نشد.');}}}
  Future<void> save({String? title,String? description,String? username,bool? public,bool? approval,bool? adminsPost,bool? adminsAdd,bool? reactions})async{if(!canManage||c==null||busy)return;final x=c!;setState(()=>busy=true);try{await db.rpc('update_group_settings',params:{'p_conversation_id':widget.conversationId,'p_title':title??x['title'],'p_description':description??x['description'],'p_avatar_url':x['avatar_url'],'p_is_public':public??x['is_public']??false,'p_username':username??x['username'],'p_join_approval':approval??x['join_approval']??false,'p_only_admins_can_post':adminsPost??x['only_admins_can_post']??true,'p_only_admins_can_add':adminsAdd??x['only_admins_can_add']??false,'p_auto_delete_seconds':x['auto_delete_seconds']??0,'p_allow_reactions':reactions??x['allow_reactions']??true});await load();}catch(e){toast('ذخیره نشد: $e');}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> edit()async{if(!canManage||c==null)return;final t=TextEditingController(text:'${c!['title']??widget.title}'),d=TextEditingController(text:'${c!['description']??''}'),u=TextEditingController(text:'${c!['username']??''}');await showDialog(context:context,builder:(q)=>AlertDialog(title:const Text('ویرایش کانال'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'نام کانال')),TextField(controller:u,decoration:const InputDecoration(labelText:'نام کاربری',prefixText:'@')),TextField(controller:d,maxLines:3,decoration:const InputDecoration(labelText:'توضیحات'))]),actions:[TextButton(onPressed:()=>Navigator.pop(q),child:const Text('لغو')),FilledButton(onPressed:(){Navigator.pop(q);save(title:t.text.trim(),description:d.text.trim(),username:u.text.trim().replaceFirst('@',''));},child:const Text('ذخیره'))]));t.dispose();d.dispose();u.dispose();}
  Future<void> delete()async{if(!owner||busy)return;final ok=await showDialog<bool>(context:context,builder:(q)=>AlertDialog(title:const Text('حذف کامل کانال'),content:const Text('کانال و پیام‌های آن برای همه حذف می‌شود.'),actions:[TextButton(onPressed:()=>Navigator.pop(q,false),child:const Text('لغو')),FilledButton(onPressed:()=>Navigator.pop(q,true),child:const Text('حذف دائمی'))]))??false;if(!ok)return;setState(()=>busy=true);try{await db.rpc('delete_channel',params:{'p_conversation_id':widget.conversationId});if(mounted)Navigator.pop(context,true);}catch(e){toast('حذف ناموفق بود: $e');}finally{if(mounted)setState(()=>busy=false);}}
  @override void initState(){super.initState();load();}
  @override Widget build(BuildContext context){if(loading)return Scaffold(appBar:AppBar(title:const Text('مدیریت کانال')),body:const AppSkeletonList(count: 6));final x=c!;return Scaffold(appBar:AppBar(title:const Text('مدیریت کانال')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.campaign)),title:Text('${x['title']??widget.title}',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${x['username']==null||x['username'].toString().isEmpty?'بدون نام کاربری':'@${x['username']}'}\n${x['is_public']==true?'عمومی':'خصوصی'}'))),Card(child:Column(children:[ListTile(leading:const Icon(Icons.edit),title:const Text('ویرایش پروفایل کانال'),onTap:canManage?edit:null),const Divider(height:1),ListTile(leading:const Icon(Icons.link),title:const Text('لینک کانال'),subtitle:const Text('ساخت، کپی، اشتراک‌گذاری و باطل کردن'),onTap:canManage?()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ConversationInvitePage(conversationId:widget.conversationId,title:widget.title,type:'channel'))):null)])),Card(child:Column(children:[SwitchListTile(title:const Text('فقط مدیران پیام بفرستند'),value:x['only_admins_can_post']??true,onChanged:canManage?(v)=>save(adminsPost:v):null),const Divider(height:1),SwitchListTile(title:const Text('تأیید عضویت'),value:x['join_approval']??false,onChanged:canManage?(v)=>save(approval:v):null),const Divider(height:1),SwitchListTile(title:const Text('فقط مدیران عضو اضافه کنند'),value:x['only_admins_can_add']??false,onChanged:canManage?(v)=>save(adminsAdd:v):null),const Divider(height:1),SwitchListTile(title:const Text('واکنش‌ها'),value:x['allow_reactions']??true,onChanged:canManage?(v)=>save(reactions:v):null),const Divider(height:1),SwitchListTile(title:const Text('کانال عمومی'),value:x['is_public']??false,onChanged:canManage?(v)=>save(public:v):null)])),Card(child:ListTile(leading:const Icon(Icons.delete_forever),title:const Text('حذف کامل کانال'),subtitle:const Text('فقط مالک کانال'),onTap:owner?delete:null)),if(busy)const Padding(padding:EdgeInsets.all(16),child:Center(child:CircularProgressIndicator()))]));}
}
